# Generated by Django 3.0.6 on 2020-07-22 03:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Configrations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_body',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='followers',
            name='followers',
            field=models.ManyToManyField(blank=True, to='Configrations.Profile'),
        ),
        migrations.AlterField(
            model_name='following',
            name='following',
            field=models.ManyToManyField(blank=True, to='Configrations.Profile'),
        ),
        migrations.AlterField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tagged',
            name='tagged_people',
            field=models.ManyToManyField(blank=True, to='Configrations.Profile'),
        ),
    ]
