# Generated by Django 3.0.6 on 2020-07-25 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Configrations', '0002_bookmark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(default='default/anon.png', upload_to='profile_pics'),
        ),
    ]
