# Generated by Django 3.0.6 on 2020-07-30 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Configrations', '0006_followrequestmassage_followrequests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followrequests',
            name='requests',
            field=models.ManyToManyField(blank=True, to='Configrations.FollowRequestMassage'),
        ),
    ]
