# Generated by Django 3.0.6 on 2020-08-06 05:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Configrations', '0008_story'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='dated',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
