# Generated by Django 3.0.6 on 2020-08-07 05:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Configrations', '0010_commentreply'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Configrations.Profile'),
        ),
        migrations.AddField(
            model_name='commentreply',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Configrations.Profile'),
        ),
    ]
