# Generated by Django 3.0.6 on 2020-08-09 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Configrations', '0011_auto_20200806_2143'),
    ]

    operations = [
        migrations.AddField(
            model_name='followrequestmassage',
            name='seen',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Story',
        ),
    ]
